### ISSUE TITLE
Add mods from folder doesn't work

### ISSUE THREAD

**Issue by TTSKarlsson** [Artentus/ModMyFactory#69]
It doesn't find any valid mods. Tested directly from a mods folder in a working server.

**Comment by Artentus** [comment]
Actually this is expected bahaviour. The "add from folder" option only adds one extracted mod. To use it select the folder that contains the info.json file of the mod you want to add.

If you want to add multiple mods at once use the "add from files" option and multi-select all mods yoiu want to add. Extracted mods are not supported by this method because of technical limitations.
