### ISSUE TITLE
Allow to filter for supported factorio versions

### ISSUE THREAD

**Issue by arnemertz** [Artentus/ModMyFactory#72]
When downloading mods, we can filter for names. However, the lists still contain lots of mods that have not been updated for the current factorio version. It would be useful to be able to restrict the list of mods to those that are compatible with factorio 0.16 (0.17, 0.18...)

**Comment by ghost** [comment]
I created a very hacky version to do this, the Factorio version is hardcoded because I couldn't find where the program stores that. I give no support for it, but I thought it might possibly be useful to someone.
https://github.com/HiddenKn/ModMyFactory/commit/1497cb17c4269c5f5fbd989d13b347aecd672063

Just realized that this only works for the latest version of the mod, so it might not be perfect if you want to filter for older versions of Factorio.

**Comment by Artentus** [comment]
I have implemented this now finally for the upcoming version 1.7.1.

However there is a catch: the API is actually limiting what I can realistically do here sadly. The complete mod list only returns information about the very latest release of a mod. That means I can only use the Factorio version of the latest release for filtering. For example if a mod has been released for both 0.15 and 0.16, if you filter by Factorio version the mod will only be listed under 0.16.

This is not optimal, however the only way to consider all available Factorio versions is to query the full release list of each mod from the sever. Considering how long it takes to query this information from the server for a single mod (in MMF this happens when clicking on a mod in the list) loading the entire list of currently over 3000 mods would take at least an hour, and that is also a generous estimate.

**Comment by HiddenKn** [comment]
Sorry if this sounds a bit mean but your code is exactly the same as my code so I have reason to believe you used it. Would you mind attributing me somewhere (the readme or with a co-author commit)? I would really appreciate it.

**Comment by ghost** [comment]
Sorry about that comment. I'm stupid and blind.

**Comment by ghost** [comment]
Thank you for your hard work on ModMyFactory, by the way.

**Comment by arnemertz** [comment]
Thanks so much for the feature! I guess due to the rapid development of Factorio, the vast majority of use cases for this will be to filter for the latest Factorio version. So, the limitation you mention should be fine.
