### ISSUE TITLE
Description doesn't update

### ISSUE THREAD

**Issue by savanik** [Artentus/ModMyFactory#86]
In the 'Browse online mods' window, after using the search bar to find a mod, when you select a mod, the description shows up in the right hand pane.

When you select a second mod, the description remains the same as the first mod you selected.

**Comment by Artentus** [comment]
Are you running version 1.12pre4? It's possible this kind of behaviour was broken in earlier versions, the API changed at one point.

**Comment by savanik** [comment]
I am running the latest release listed on the distribution page, which
is ModMyFactorio v.1.5.11, published Aug 27, 2017. All the others since
then are listed as pre-release versions.

**Comment by Artentus** [comment]
Yea don't run that version, it doesn't work. I have left a redirect in the release notes leading to the correct version.

There is no stable 1.5.12 yet because I still haven't figured out yet how to restore all of the previous functionality from before the mod portal update. However, the core functionality is at least working while in 1.5.11 all online-functionality is broken. Can't download mods, can't update mods.
